[tools]
python = "3.12"

[env]
_.python.venv = { path = "venv", create = true }

[tasks.install]
run = "pip install -e '.[dev]'"

[tasks.test]
run = "pytest"

[tasks.format]
run = "black . && isort ."

[tasks.lint]
run = "pylint m3u_parser"
