[tool.black]
line-length = 119
skip-string-normalization = true
target-version = ['py37', 'py38', 'py39', 'py310', 'py311', 'py312', 'py313']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | dist
  | venv
)/
'''

[tool.isort]
line_length = 119
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true

[tool.semantic_release]
version_variable = "setup.py:VERSION"
upload_to_pypi = true
upload_to_release = true
hvcs = "github"
branch = "main"
